// syscall.h - support for junction syscalls

#pragma once

#include <syscall.h>

#include "junction/kernel/ksys.h"
#include "junction/kernel/usys.h"

// The syscall table has one slot per Linux syscall number plus a handful of
// slots that hold Junction's own entry trampolines. Linux numbers end in the
// 460s today (fchmodat2 is 452, map_shadow_stack 453) and grow by a few per
// release, so the trampolines live at the top of a 512-slot table: 507-511,
// well clear of anything Linux will assign soon. 512 slots of 8 bytes is
// exactly one page at SYSTBL_TRAMPOLINE_LOC. The guest glibc hardcodes the
// trampoline addresses (JUNCTION_ENTRY_* in sysdeps/unix/sysv/linux/x86_64/
// sysdep.h, patch 0005), as does the vdso (syscall/vdso/vdso.S); the three must
// agree.
#define SYS_NR 512
#define SYSTBL_TRAMPOLINE_FIRST 507
#define SYSTBL_TRAMPOLINE_LOC (0x200000UL)

namespace junction {

extern "C" typedef int64_t (*sysfn_t)(int64_t, int64_t, int64_t, int64_t,
                                      int64_t, int64_t);

// generated by systbl.py
extern "C" sysfn_t sys_tbl[SYS_NR];
extern sysfn_t sys_tbl_strace[SYS_NR];
extern const char *syscall_names[SYS_NR];
}  // namespace junction
